# Generated by Django 4.1.9 on 2024-11-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
