# Generated by Django 4.1.9 on 2024-10-31 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_carmodel_carimage_usercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='comment',
            new_name='car',
        ),
    ]
